name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [9.*, 10.*, 11.*, 12.*]
        dependency-version: [prefer-stable]
        exclude:
          - php: 8.1
            laravel: 11.*
          - php: 8.1
            laravel: 12.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, iconv, intl
        coverage: none

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
        if [[ "${{ matrix.laravel }}" == "12.*" ]]; then
          composer require "orchestra/testbench:^10.0" --no-interaction --no-update
          composer require "phpunit/phpunit:^11.5.3" --no-interaction --no-update
        elif [[ "${{ matrix.laravel }}" == "11.*" ]]; then
          composer require "orchestra/testbench:^9.0" --no-interaction --no-update
          composer require "phpunit/phpunit:^11.5.3" --no-interaction --no-update
        elif [[ "${{ matrix.laravel }}" == "10.*" ]]; then
          composer require "orchestra/testbench:^8.0" --no-interaction --no-update
          composer require "phpunit/phpunit:^10.1" --no-interaction --no-update
        elif [[ "${{ matrix.laravel }}" == "9.*" ]]; then
          composer require "orchestra/testbench:^7.0" --no-interaction --no-update
          composer require "phpunit/phpunit:^9.5.10" --no-interaction --no-update
        fi
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

    - name: Execute tests (Unit and Feature)
      run: vendor/bin/phpunit
